# Generated by Django 3.1.14 on 2022-09-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('title_en', models.TextField(blank=True, verbose_name='Название на английском')),
                ('title_ja', models.TextField(blank=True, verbose_name='Название на японском')),
                ('image', models.ImageField(blank=True, default='None', upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Развитие')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True, verbose_name='Точка координат')),
                ('lon', models.FloatField(null=True, verbose_name='Точка координат')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Дата появления')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Дата исчезновения')),
                ('level', models.IntegerField(blank=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, verbose_name='Атака')),
                ('defence', models.IntegerField(blank=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
